### PR TITLE
#152919356 Reset Cache on Muscle Delete 

### PR DESCRIPTION
**Pull request by Sekams**
#### What does this PR do?
Delivers the `Exercise cache when deleting muscles` feature
#### Description of Task to be completed?
The feature resets the cache of the exercises whenever a muscle is deleted.
#### How should this be manually tested?
The feature can be manually tested by running the following command:
```./manage.py test wger.exercises.tests.test_exercise.ExercisesCacheTestCase.test_exercise_cache_resets_muscle_delete```
#### Any background context you want to provide?
This feature is meant for the administrator user accounts only
#### What are the relevant pivotal tracker stories?
[#152919356](https://www.pivotaltracker.com/story/show/152919356)
#### Questions:

### CODE REVIEW

**Review by Andretalik — CHANGES_REQUESTED** [review]
You should not push commented out code.
Remove it.

**Review by Andretalik — CHANGES_REQUESTED** [review]
in test_exercise.py.
 - That one test has a lot of assert statements when its a single test.
 - The assertEqual(s) on line 501, 510, 511, 514 522 don't have a message if they fail.

The test you have written is not a unittest since you are testing several things all at once i.e: Adding of an exercise, saving it, deleting it then making sure that the cache has been cleared.
If there are tests for the adding of a muscle, saving it and deleting it, why include them yet again in your test(DRY code)? In the event that there aren't any, write unittests for them.

**Comment by sekams** [comment]
@Andretalik, I have worked on the changes you suggested. Let me know what you think

**Comment by Andretalik** [comment]
Why has the coverage decreased?

**Comment by sekams** [comment]
It is because of some changes in the `wger/core/views/user.py ` file that I pulled from `develop` when I was rebasing

screen shot 2017-12-14 at 11 22 56 am

**Comment by Andretalik** [comment]
Can anything be done about that?

**Comment by sekams** [comment]
Working with @Arthur236 and @machariamarigi to see a way forward

**Review by Andretalik — APPROVED** [review]

**Pull request merged**
