### PR TITLE
#153505619 Host wger on heroku 

### PR DESCRIPTION
**Pull request by arnawldo**
#### What does this PR do?
Makes app available online on Heroku
#### Description of Task to be completed?
Deploy application on Heroku
#### How should this be manually tested?
Open app [here](https://wger-apollo.herokuapp.com)
#### What are the relevant pivotal tracker stories?
[153505619 ](https://www.pivotaltracker.com/story/show/153505619)
#### Questions:

### CODE REVIEW

**Review by Andretalik — CHANGES_REQUESTED** [review]
Coverage has dropped. Anything to comment as to why?

**Comment by arnawldo** [comment]
I think it's from a rebase I did during my task. Coverage dropped in wger/core files but I didn't touch any of them. Don't know which task was related to (or who did) the changes though

**Comment by Andretalik** [comment]
Seems unlikely that coverage can drop without a reason, right? Try to find out what the issue is by EOD.

**Comment by arnawldo** [comment]
On it

**Comment by arnawldo** [comment]
I failed to find the commits for the changed code that reduced coverage. Must done my rebase poorly. I have created a cleaner PR for the deployment [here](https://github.com/andela/wg-apollo/pull/20)

**Comment by Andretalik** [comment]
If you've opened another one, you close this one.

**Pull request closed without merging**
